language: node_js
node_js:
- 0.12
- 4
- 5
- 6
env:
  - MONGOOSE_VERSION=3.8
matrix:
  include:
    - node_js: 4
      env: MONGOOSE_VERSION=4
      env: MONGOOSE_VERSION=3.7
      env: MONGOOSE_VERSION=3.6
      env: MONGOOSE_VERSION=3.5
      env: MONGOOSE_VERSION=3.4
      env: MONGOOSE_VERSION=3.3
      env: MONGOOSE_VERSION=3.2
      env: MONGOOSE_VERSION=3.1
      env: MONGOOSE_VERSION=3.0
before_script:
  - npm install mongoose@$MONGOOSE_VERSION
services:
  - mongodb